Mishal api
misusonu18/digital-visiting-card-js pull request #1
Opened 2022-03-10 14:22 UTC by misusonu18

2022-03-15 05:28 UTC, hirenkeraliya requested changes

2022-03-15 05:28 UTC, hirenkeraliya commented on functions/create.js
> +        const d = new Date();
what is `d`?

2022-03-15 05:28 UTC, hirenkeraliya commented on functions/create.js
> +const axios = require("axios");
filename `createNewCard.js`

2022-03-15 05:28 UTC, hirenkeraliya commented on functions/getThePhoneNumber.js
> +            url: 'https://api.github.com/repos/misusonu18/digital-visiting-card-js/contents/js/phone_number.json',
filename `phone_numbers.json`

2022-03-15 05:28 UTC, hirenkeraliya commented on functions/getThePhoneNumber.js
> +const axios = require("axios");
filename `fetchPhoneNumbers.js`

2022-03-15 05:28 UTC, hirenkeraliya commented on functions/read.js
> +const axios = require("axios");
filename `getVisitingCards.js`

2022-03-15 05:28 UTC, hirenkeraliya commented on functions/readOneFile.js
> +const axios = require("axios");
filename `getSpecificVisitingCard.js`

2022-03-15 05:28 UTC, hirenkeraliya commented on functions/update.js
> +const axios = require("axios");
filename `updateVisitingCard.js`

2022-03-15 05:28 UTC, hirenkeraliya commented on functions/updateThePhoneNumber.js
> +const axios = require("axios");
filename `updatePhoneNumbersList.js`

2022-03-15 05:28 UTC, hirenkeraliya commented on js/app.js
> +var userEmail, user;
why declare variable outside?

2022-03-15 05:28 UTC, hirenkeraliya commented on js/app.js
> +}
move this code to top of the file

2022-03-15 05:28 UTC, hirenkeraliya commented on js/app.js
> +    sessionStorage.removeItem('file-data');
make proper naming of the local storage key

2022-03-15 05:28 UTC, hirenkeraliya commented on js/app.js
> +    }, 5000);
why timeout?

2022-03-15 05:28 UTC, hirenkeraliya commented on js/card.js
> +getFileData = sessionStorage.getItem("file-data-card");
who will declare the variable?

2022-03-15 05:28 UTC, hirenkeraliya commented on js/card.js
> +let card = document.getElementById('card');
`card` variable is not used in the whole file.

2022-03-15 05:28 UTC, hirenkeraliya commented on js/card.js
> +let whatsapp = document.getElementById('whatsapp');
why variables do it directly

2022-03-15 05:28 UTC, hirenkeraliya commented on js/card.js
> +let whatsapp = document.getElementById('whatsapp');
When you do code javascript code using the var instead of the let. I think all the browsers are not supported let. Do Some research on this.

2022-03-15 05:28 UTC, hirenkeraliya commented on js/getAllData.js
> +displayLoading();
filename `fetchAllVisitingCards.js`

2022-03-15 05:28 UTC, hirenkeraliya commented on js/getAllData.js
> +                        >
use template tag instead of the html coding inside javascript

2022-03-15 05:28 UTC, hirenkeraliya commented on js/manage.js
> +        emailFlag = true;
else not needed. Do some refactoring

2022-03-15 05:28 UTC, hirenkeraliya commented on js/manage.js
> +        emailFlag = true;
Check all the validation errors.

2022-03-15 05:28 UTC, hirenkeraliya commented on js/manage.js
> +        //
if not needed then remove the code

2022-03-15 05:28 UTC, hirenkeraliya commented on js/manage.js
> +        //
unnecessary code remove if it's not required.

2022-03-23 11:24 UTC, hirenkeraliya approved these changes

2022-03-23 14:08 UTC, gauravmak requested changes

2022-03-23 14:08 UTC, gauravmak commented on functions/updateVisitingCard.js
> +        let response = JSON.parse(event.body);
Use `const` wherever possible

2022-03-25 04:42 UTC, gauravmak commented on functions/createNewCard.js
> +            url: 'https://api.github.com/repos/misusonu18/digital-visiting-card-js/contents/js/' + folderName + '/' + fileName,
This cannot be static `misusonu18/digital-visiting-card-js`

2022-03-25 04:42 UTC, gauravmak commented on functions/createNewCard.js
> +        const response = JSON.parse(event.body);
```suggestion
        const eventBody = JSON.parse(event.body);
```

2022-03-25 04:42 UTC, gauravmak commented on functions/createNewCard.js
> +        const responseData = response.data;
```suggestion
        const cardDetails = response.data;
```

2022-03-25 04:42 UTC, gauravmak commented on functions/createNewCard.js
> +            .then(function (testResponse) {
```suggestion
            .then(function (response) {
```

2022-03-25 04:42 UTC, gauravmak commented on functions/createNewCard.js
> +            statusCode: 201,
The status code should be 201 only if the API call is successful, right?

2022-03-25 04:42 UTC, gauravmak commented on functions/createNewCard.js
> +            statusCode: 404,
When does this happen?

2022-03-25 04:42 UTC, gauravmak commented on functions/createNewCard.js
> +                msg: (responseMessage.data.content.name == fileName) ? "Successfull File Created" : "Something Went Wrong",
`Successfull File Created` -> `Card created successfully`

2022-03-25 04:42 UTC, gauravmak commented on js/app.js
> +    user = localStorage.getItem('gotrue.user');
What is `gotrue.user`?

2022-03-25 04:42 UTC, gauravmak commented on js/app.js
> +    localStorage.setItem('username', userEmail.split("@")[0]);
Why is username set like this?

2022-03-25 04:42 UTC, gauravmak commented on js/app.js
> +let loader = document.querySelector("#loading");
Convert to `const`

Check again everywhere. Convert `var` to `const` too.

2022-03-25 04:42 UTC, gauravmak commented on js/app.js
> +}
What is this for?

2022-03-25 04:42 UTC, gauravmak commented on js/app.js
> +}
What is this for?

2022-03-25 04:50 UTC, gauravmak requested changes

2022-03-25 04:50 UTC, gauravmak commented on js/card.js
> +document.getElementById('whatsapp').href = 'https://wa.me/' + visitingCardData.phone_number;
The phone number may not be the same as the Whatsapp number. Keep a separate field for the same.

2022-03-25 04:50 UTC, gauravmak commented on js/card.js
> +document.getElementById('website').href = visitingCardData.website
Do not display the element if the data is not set. Make sure that design looks good even when none of the optional fields are set.

2022-03-25 04:50 UTC, gauravmak commented on js/fetchAllVisitingCards.js
> +axios.post(
Why post request?

2022-03-25 04:50 UTC, gauravmak commented on js/fetchAllVisitingCards.js
> +    }
Move all these to a readable function

2022-03-25 04:50 UTC, gauravmak commented on js/fetchAllVisitingCards.js
> +        const data = atob(res.data.data.content);
atob?

2022-03-25 04:50 UTC, gauravmak commented on js/manage.js
> -let firstNameInput = document.getElementById('first-name');
This file is too big. I am not checking now.

2022-03-25 04:51 UTC, gauravmak commented
@misusonu18 This is the last warning for you. MAKE SMALLER PRS.

Am closing this. Create new smaller PRs out of these.

@hirenkeraliya Do not let anyone create huge PRs like this. Feel free to close and let them do the work again.

2022-03-25 04:51 UTC, closed without merging