Mishal create card pr
misusonu18/digital-visiting-card-js pull request #2
Opened 2022-03-25 12:40 UTC by misusonu18

2022-03-28 10:52 UTC, hirenkeraliya requested changes

2022-03-28 10:52 UTC, hirenkeraliya commented on js/app.js
> +	let userEmail = user = '';
tab?

2022-03-28 10:52 UTC, hirenkeraliya commented on js/manage.js
> +			fileName = (nameInput.value).replace(' ', '_') + '_' + seconds + '.json';
tab?

2022-03-28 10:52 UTC, hirenkeraliya commented on js/manage.js
> +}
proper indentation by spaces.

2022-03-28 10:52 UTC, hirenkeraliya commented on js/manage.js
> +        '/.netlify/functions/updatePhoneNumbersList', {
use netlify redirects.

2022-03-28 13:19 UTC, hirenkeraliya requested changes

2022-03-28 13:19 UTC, hirenkeraliya commented on Readme.md
> +3. Setup the variable
Add steps for the deployement

2022-03-28 13:19 UTC, hirenkeraliya commented on js/manage.js
> +    if (phoneNumberFlag == true && emailFlag == true && nameFlag == true && websiteFlag == true && githubFlag == true) {
```
if (phoneNumberFlag != true || emailFlag != true || nameFlag != true || websiteFlag != true || githubFlag != true) {
    return;
}
```

2022-03-29 10:57 UTC, hirenkeraliya approved these changes

2022-03-29 12:28 UTC, gauravmak requested changes

2022-03-29 12:28 UTC, gauravmak commented on functions/updatePhoneNumbersList.js
> +                msg: (responseMessage.data.content.name == 'validate_phone_numbers.json') ? "Successfull File Updated" : "Something Went Wrong",
Check message

2022-03-30 11:43 UTC, merged