code: displays the visiting card wih specific details
misusonu18/digital-visiting-card-js pull request #4
Opened 2022-03-30 13:15 UTC by misusonu18

# Display the visiting cards

2022-04-01 11:02 UTC, hirenkeraliya approved these changes

2022-04-01 12:36 UTC, gauravmak requested changes

2022-04-01 12:36 UTC, gauravmak commented on js/fetchAllVisitingCards.js
> +        allData.forEach(element => {
Load only 2 records by default. The user has to click on `Load More` for more cards.

2022-04-08 10:40 UTC, hirenkeraliya approved these changes

2022-04-09 04:53 UTC, gauravmak requested changes

2022-04-09 04:53 UTC, gauravmak commented on js/fetchAllVisitingCards.js
> +        if (i < 2) {
break the loop if `i > 1` instead.

2022-04-11 04:49 UTC, merged